### PR TITLE
Add Cheshire Cat to community integrations

### PR DESCRIPTION
**Pull request by pieroit**
We have an Ollama adapter (subclassing langchain to make it both sync and async) and also created a [setup tutorial](https://cheshirecat.ai/local-models-with-ollama/)

### CODE REVIEW

**Comment by jmorganca** [comment]
Hi! Thanks so much for the PR @pieroit. I might have missed it, but on scanning the repo I didn't see any documentation on how to use Ollama with that project – how would one get started? Thanks

**Comment by pieroit** [comment]
Hi @jmorganca glad to communicate with you, we really like Ollama.
At the moment from the admin you go to LLM settings you find Ollama and you can give the address, choose model and another few options

image


We have a [tutorial on the website](https://cheshirecat.ai/local-models-with-ollama/) and a [repo](https://github.com/cheshire-cat-ai/local-cat) with a docker-compose setup Cat + Ollama + local Embedder + Qdrant 

@valentimarco and @pingdred are trying to make langchain's Ollama adapter work with async/await (at the moment it only seems to support sync calls, we are investigating)

Some things are still buggy, but you know how it works in open source :)

**Review by BruceMacD — APPROVED** [review]
Thanks for the contribution, this is an interesting project

**Comment by pieroit** [comment]
> Thanks for the contribution, this is an interesting project

Hi @BruceMacD thanks
Any chance you guys are interested in a more active collab?
Let's talk about it! I'll try to contact you

**Pull request merged**
