### PR TITLE
Let ollama test your Hiragana knowledge.

### PR DESCRIPTION
**Pull request by stephenwithav**

### CODE REVIEW

**Comment by technovangelist** [comment]
I think these could be great if you push the model to your account and then share them with folks.

**Comment by stephenwithav** [comment]
The README lacks instructions for adding a registry to push to.  Can you help me with this error?

```
Error: unable to push library/book-summary, make sure this namespace exists and you are authorized to push to it
```

I'm about to create a personal repo with my Modelfiles.

**Comment by technovangelist** [comment]
Visit ollama.ai/signup or click the sign in link at the top of the page and choose to create an account. Then you can create a namespace that you can push to.

**Comment by stephenwithav** [comment]
Thank you for your help, @technovangelist.  I created an ed25519 key in ~/.ollama/, uploaded the public key to ollama.ai, and tried pushing with `ollama push stephenwithav/book-summary`, but I'm getting:

```
Error: unable to push stephenwithav/book-summary, make sure this namespace exists and you are authorized to push to it
```

Can you offer any suggestions?

**Comment by mxyng** [comment]
If you're on Linux, the key path is actually `/usr/share/ollama/.ollama/id_ed25519.pub`

**Comment by mxyng** [comment]
Closing this PR. If you continue to have issues with pushing, please create an issue

**Pull request closed without merging**
