### PR TITLE
Add support for additional template instructions

### PR DESCRIPTION
**Pull request by nathanleclaire**
This PR adds support for Sprig library of template functions, as well as a custom "exec" function that can run commands on the user's computer. This enables fun and novel use cases like including randomness (Roll a d20 if needed?) analyzing local system details/data and more.

Prototype/thought experiment: What if you could dramatically expand what the Modelfile templates could do by adding [Sprig](http://masterminds.github.io/sprig/) as well as custom commands like `exec` that will provide users with the ability to do things on their computer? 

Two new examples to demonstrate the idea.

### `history`

Which will set the context's "date" to a random previous era, making the characters generated relatively novel:

**Einstein**
Screenshot 2023-07-19 at 5 02 24 PM

**Benjamin Franklin**
Screenshot 2023-07-19 at 5 05 12 PM

**Thomas Jefferson**
Screenshot 2023-07-19 at 5 05 51 PM

### `top` 

Which uses `top` to performance an analysis of the user's desktop system.

Screenshot 2023-07-19 at 5 23 14 PM

### CODE REVIEW

**Comment by nathanleclaire** [comment]
That being said, I fucking hate Go templates. Hear me out, what if you used https://github.com/dop251/goja to set the params and user/system/context details, and to make chains that don't suck.

**Comment by pdevine** [comment]
hey @nathanleclaire, I'd be super nervous about having exec run something on your machine, because that could be a massive security nightmare. I'll have to think about that some more though. Like maybe there's a way to sandbox things.

**Comment by nathanleclaire** [comment]
> hey @nathanleclaire, I'd be super nervous about having exec run something on your machine, because that could be a massive security nightmare. I'll have to think about that some more though.

Yea, this isn't necessarily a direct request for merge, more of a sketch of an idea. 

> Like maybe there's a way to sandbox things.

Yea, like run a container or container equivalent where some things are mounted in read only.

**Comment by nathanleclaire** [comment]
Since this is really more of an exploration that request for merge, I'm gonna close, but want to keep exploring related ideas.

**Pull request closed without merging**
