### PR TITLE
Updated instructions for Jetson setup and minimized requirements

### PR DESCRIPTION
**Pull request by bnodnarb**
Revised NVIDIA Jetson tutorial to be simpler and also added a quickstart guide.

### CODE REVIEW

**Comment by jmorganca** [comment]
Thanks do you know if `tmux` is a requirement? (thinking where we can simplify this example)

**Comment by bnodnarb** [comment]
Thanks for the recommendation, @jmorganca - I've gone ahead and set it up to use a `nohup` command instead. Thanks again!

**Comment by bnodnarb** [comment]
Hi @jmorganca - I made a few more tweaks (done now). Thanks and have a great morning!

**Comment by bnodnarb** [comment]
Hi @jmorganca - I'm super excited about the latest release (v0.1.13). Now that we can set parameters in `ollama run`, I will revise the setup instructions related to this PR (thanks @BruceMacD for keeping me updated on that). I will post a comment when this PR has been updated accordingly and is ready for review. Thanks, all!

**Comment by bnodnarb** [comment]
Hi @jmorganca - this PR has been updated. Thanks!

**Pull request closed without merging**
