### PR TITLE
Use build tags to generate accelerated binaries for CUDA and ROCm on …

### PR DESCRIPTION
**Pull request by 65a**
…Linux. The binary will detect and use the accelerated runtimes embedded in it. The build tags rocm or cuda must be specified to both go generate and go build. ROCm builds should have both ROCM_PATH set (and the ROCM SDK present) as well as CLBlast installed (for GGML) and CLBlast_DIR set in the environment to the CLBlast cmake directory (likely /usr/include/cmake/CLBlast). Build tags are also used to switch VRAM detection between cuda and rocm implementations.

It's recommended to also set AMDGPU_TARGETS and GPU_TARGETS when building to ensure card coverage, an example might be `AMDGPU_TARGETS='gfx900;gfx906;gfx1030;gfx1100' GPU_TARGETS='gfx900;gfx906;gfx1030;gfx1100'`

### CODE REVIEW

**Comment by 65a** [comment]
Back to draft, need to handle the cpu only case better

**Comment by 65a** [comment]
Build command example for ROCm and support various common cards, and use CLBlast for GGML files:
```
AMDGPU_TARGETS=gfx900,gfx906,gfx1030,gfx1100 ROCM_PATH=/opt/rocm CLBlast_DIR=/usr/lib/cmake/CLBlast go generate -tags rocm ./...
go build -tags rocm
```

**Comment by 65a** [comment]
Works on gfx906 (Mi60-ish card), and gfx1030 (RX6950XT). The low VRAM 6700s (which also lacks official ROCm support) seems to be running into various issues with memory alignment similar to https://github.com/RadeonOpenCompute/ROCm/issues/2480 but if I can get that sorted, it's a good testbed for the offloading heuristic.

Here are some generation stats from the RX6950XT running a q6k of a 13B model:
```
llama_print_timings:      sample time =     6.98 ms /    14 runs   (    0.50 ms per token,  2005.16 tokens per second)
llama_print_timings: prompt eval time =   153.99 ms /    32 tokens (    4.81 ms per token,   207.80 tokens per second)
llama_print_timings:        eval time =   308.87 ms /    13 runs   (   23.76 ms per token,    42.09 tokens per second)
```

**Comment by 65a** [comment]
Let me know if you want docs/dockerfile updates/etc in the same PR. This also should allow for something like #597 by specifying no tags for the slim image.

**Comment by 65a** [comment]
The pinned version of llama.cpp has generation issues on gfx906 (Instinct Mi60), which are resolved in llama.cpp HEAD, fyi.  This manifests as high GPU utilization and very low token rate, at least a 10x slowdown. It's not as bad on gfx1030. Recommend bumping `gguf` submodule pointer.

**Comment by BruceMacD** [comment]
updated the gguf submodule in #710

**Comment by 65a** [comment]
Rebased on HEAD

**Comment by 65a** [comment]
Add dockerfile updates to preserve current behavior.

**Comment by 65a** [comment]
This also wants #724 or similar, my local version was to allocate 3 additional layers worth of (v)RAM(k, v, cache), but % based would also work

**Comment by 65a** [comment]
Added docs

**Comment by 65a** [comment]
Added compatibility with #724 for cuda  (check free not total), and rocm already does something like that. For the additional reservation on constrained devices, either approach sounds good to me, but I put my local change here to reserve 3 layers (which I think is the problem... 2 layers + VRAM cache).

**Comment by 65a** [comment]
Rebased on head and merged in #724

**Comment by 65a** [comment]
Note, this required #752 to switch between models successfully with `ollama run`, I locally patched it in from that PR, it should go first.

- ✅ clean-checkout compile tested
- ✅ tested GGML inference tested on gfx906 [CLBlast]
- ✅ tested GGUF inference tested on gfx906 [ROCm]

**Comment by Sir-Photch** [comment]
Couldn't wait for this to be merged so I build your branch, and I can confirm this works on my 6700XT! I've set `AMDGPU_TARGETS="gfx1030"` for this. (And `HSA_OVERRIDE_GFX_VERSION=10.3.0` for compatability with my GPU.)

This is very cool!

**Comment by grigio** [comment]
@Sir-Photch Cool, can you share some benchmarks? model and token/s ?

**Comment by Sir-Photch** [comment]
How do I benchmark ollama?

**Comment by 65a** [comment]
Rebased on HEAD. @BruceMacD or @jmorganca anything else you are looking for here to review or merge?

**Comment by 65a** [comment]
Quick benchmark/test result with [this file](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q8_0.gguf) on RX6950XT [gfx1030]

```
llama_print_timings:        load time =   642.95 ms
llama_print_timings:      sample time =     8.60 ms /    19 runs   (    0.45 ms per token,  2210.07 tokens per second)
llama_print_timings: prompt eval time =    76.28 ms /    11 tokens (    6.93 ms per token,   144.22 tokens per second)
llama_print_timings:        eval time =   330.34 ms /    18 runs   (   18.35 ms per token,    54.49 tokens per second)
llama_print_timings:       total time =   416.14 ms
```

**Comment by 65a** [comment]
Welp, that merge didn't go so well. Will repush after merging the changes properly.

**Comment by 65a** [comment]
I'm going to open a new pull as I think I cannot reopen an old pull here, and github is excessively aggressive about closing them automatically  :(

**Pull request closed without merging**
