### PR TITLE
fix: allow extension origins (still needs explicit listing), fixes #1686

### LINKED ISSUE #1686: OLLAMA_ORIGINS=chrome-extension://etc does not work
```
(base) ➜  ~ OLLAMA_ORIGINS=chrome-extension://dofdpnoclkigpakdndmhigfojjecnfln ollama serve
2023/12/23 15:37:56 images.go:737: total blobs: 85
2023/12/23 15:37:56 images.go:744: total unused blobs removed: 0
panic: bad origin: origins must contain '*' or include http://,https://
```

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Review by mxyng — APPROVED** [review]
looks good. thanks for creating this pr

**Comment by sublimator** [comment]
@mxyng 

Thanks!

**Comment by wong2** [comment]
I believe this has been shipped in ollama v0.1.19, but I'm still getting 403 error when request from a browser extension (on macOS).

image
image

**Comment by sublimator** [comment]
you still need to explicitly list your extension with OLLAMA_ORIGINS env var

What Operating System are you using?

**Comment by wong2** [comment]
@sublimator Thanks, I see the problem. I thought AllowBrowserExtensions` means enable browser extension requests by default, I'm wrong.

**Comment by wong2** [comment]
I'm using macOS, do you know how can I restart the server with env var set?

**Comment by sublimator** [comment]
Welcome, btw, please see https://github.com/jmorganca/ollama/pull/1886

**Comment by wong2** [comment]
Thanks!

**Comment by sublimator** [comment]
Late, but "you're welcome :)"

**Comment by sublimator** [comment]
@wong2 

Seems you can make a file like:
```
~/Library/LaunchAgents/ai.ollama.origins.plist 
```

with contents similar to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ai.ollama.origins</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/launchctl</string>
        <string>setenv</string>
        <string>OLLAMA_ORIGINS</string>
        <string>chrome-
extension://dofdpnoclkigpakdndmhigfojjecnfln</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

**Comment by wong2** [comment]
@sublimator Thanks!

**Pull request merged**
