### PR TITLE
Added a minimalist React UI for Ollama models to ReadME.md

### PR DESCRIPTION
**Pull request by richawo**
I discussed it a few times in the discord, and a few people seem to be using it, so it would be good to add.

Demo video:
https://github.com/jmorganca/ollama/assets/35015261/d50f7036-cdf2-44ed-9bb0-fdbed6a4ec66

I'll be maintaining/improving it a lot over the coming weeks, and some contributors reached out to get involved.

It can now handle markdown, etc. And continues to improve beyond the initial demo.

### CODE REVIEW

**Comment by chiefMarlin** [comment]
It looks great , would be nice if this was embedded - rather than having to install npm and npm dependencies.

**Comment by richawo** [comment]
@chiefMarlin You mean publishing with the package json + node modules? or embedding the ollama serve within the project's npm call?

**Comment by chiefMarlin** [comment]
@richawo 
Ideally if we could embed the js/css/html files into this project so you can have the UI alongside the api. However i don't know if the owner of this project would be interested in that, so alternatively if we could have something that can be as portable as a golang binary that you can just download and run to get the ui as opposed to having to install npm and pull the required dependencies. In other words - maybe we could wrap the required files into a go binary ?

**Comment by richawo** [comment]
@chiefMarlin, ahh I get what you mean! Haha if @jmorganca wants to commission me to do that for the project then haha, but I dunno the direction he wants to take it. I also have big plans for what I want to do in the React app haha, since originally it was for personal use Ollama just happens to be my preferred method for handling OS LLMs :)

**Review by BruceMacD — APPROVED** [review]
Love the design, thanks for making this

**Pull request merged**
