### PR TITLE
treat `ollama run model < file` as entire prompt, not prompt-per-line

### LINKED ISSUE #568: Enter multiline text via stdin in non-interactive mode
https://github.com/jmorganca/ollama/issues/169 only addressed interactive mode, but not stdin via non-interactive mode

```
cat multiline_file | ollama run llama2
```

### PR DESCRIPTION
**Pull request by sqs**
Previously, `ollama run` treated a non-terminal stdin (such as `ollama run model < file`) as containing one prompt per line. To run inference on a multi-line prompt, the only non-API workaround was to run `ollama run` interactively and wrap the prompt in `"""..."""`.

Now, `ollama run` treats a non-terminal stdin as containing a single prompt. For example, if `myprompt.txt` is a multi-line file, then `ollama run model < myprompt.txt` would treat `myprompt.txt`'s entire contents as the prompt.

This breaks backcompat, but I believe this behavior is better than the old behavior. It is strictly more powerful than the prior behavior because callers can split a file by lines outside of Ollama and then invoke `ollama run` once per line on their own.

This is related to https://github.com/jmorganca/ollama/issues/357, but that refers to interactive usage.

Fixes #568

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]
This is great! I've been thinking about the combination as well:

```
ollama run codellama "write unit tests for this code" < main.go
```

**Comment by mxyng** [comment]
I'm unsure about this change. It's already possible to ingest an entire file using positional parameters: `ollama run  llama2 "$(cat input.txt)". It's not idiomatic nor is it obvious but it's possible.

OTOH, reading a file and processing by line is only possible by reading stdin. This is different than something like `while read LINE; do ollama run llama2 $LINE; done <$FILE` because each subsequent prompt is passed the context from the previous prompts. It makes it possible to do things like this:

```
cat <<EOF | ollama run llama2
Write a story about llamas.
Now rewrite it in the style of Shakespeare.
Now rewrite it in the style of Dr. Seuss.
EOF
```

I have been thinking about how to ingest an entire file because the current methods aren't great. Here are a few inspirations:

- `jq` `--slurp`
```
           Instead of running the filter for each JSON object in the input, read
           the entire input stream into a large array and run the filter just
           once.
```

- `xargs` `-0`
```
             Change xargs to expect NUL (``\0'') characters as separators,
             instead of spaces and newlines.  This is expected to be used in
             concert with the -print0 function in find(1).
```

There's also `--file` which can indicate a file input in addition to positional arguments, e.g.:

```
$ ollama run -f input.txt llama2 'summarize this file'
```

The downside of every options is the need for additional flags which I'm not keen on

**Comment by sqs** [comment]
My assumption: I assume `ollama run` will be primarily invoked by people building applications that use LLMs during testing, and by those applications in the background at runtime. That describes how *I* intend to use `ollama run`, at least. You all obviously have a much broader view of the userbase and your own vision, which I totally respect!

--

@jmorganca:

> This is great! I've been thinking about the combination as well:
>
> `ollama run codellama "write unit tests for this code" < main.go`

I don't think that is viable. Invoking `ollama run` in that way leaves unspecified the prompt construction and context formatting. For example, how is the final prompt actually constructed? Which parts of the file are included? Etc. All of these are absolutely critical to a good result.

---

@mxyng:

Thank you for the pointer about `ollama run llama2 "$(cat input.txt)"`. I had not thought of that, but yeah, something like that should work. Under my assumption stated above, this would be the primary way `ollama run` is invoked and would merit being the default, but that's your call.

Thank you both!

**Comment by jerzydziewierz** [comment]
this sounds like a breaking change, 
for any usages that depended on there being a single prompt per line
many automated tests might want to have this precise behaviour

I recommend to reject this change

if you need to do long prompt processing, you can always use the API endpoint method

**Comment by jmorganca** [comment]
@sqs is it possible to rebase this branch onto `main` ? otherwise happy to open a new PR from a branch in this repo if that's easier!

**Pull request closed without merging**
