### PR TITLE
set version string to current (pre)release

### PR DESCRIPTION
**Pull request by tohn**
according to the github tags and by using <https://semver.org>

### CODE REVIEW

**Comment by BruceMacD** [comment]
Hi @tohn, thanks for the contribution. We actually set this at build time rather than in code, you can see where it gets set here:
https://github.com/jmorganca/ollama/blob/d9e60f634bf420ef41fe5388b32cfda3ceb2c898/scripts/build_darwin.sh#L5

**Comment by tohn** [comment]
Ok, thanks for the hint! But I can still see the default version string on my machine (macOS 14.1.2; installed via [brew](https://formulae.brew.sh/formula/ollama)):

```bash
$ ollama -v
ollama version is 0.0.0
$ ollama --version
ollama version is 0.0.0
```

Sorry, I'm unsure where to report this.

**Comment by BruceMacD** [comment]
In the past the Homebrew maintainer took care of it, so I think an issue there may be the right place. I know they build from source to add it to the repo.

**Comment by tohn** [comment]
ftr: https://github.com/Homebrew/homebrew-core/pull/157426#issuecomment-1862806511

**Comment by chenrui333** [comment]
👋 come from homebrew side, I actually created the formula.

I wonder if it would be good to update this version.go code to consume build_version info from the environment variable? Thanks!

**Pull request closed without merging**
