### PR TITLE
Add Installation instructions for Archlinux

### PR DESCRIPTION
**Pull request by tusharhero**
Pacman is the recommended installation method. And the package is in the official repository, so makes sense to mention it in the README.

### CODE REVIEW

**Comment by technovangelist** [comment]
Thanks so much for submitting this PR. Since this is a community created package, it would be better to add it to the community integrations section at the bottom of the readme. Can you update this PR to be a link in that section?

**Comment by tusharhero** [comment]
Sure!

**Comment by tusharhero** [comment]
I am not sure about which section to put it in though.

**Comment by tusharhero** [comment]
I hope this is okay.

**Review by technovangelist — APPROVED** [review]
This is good for now. I think there are a few more out there, so as we see more installation packages, I'll probably create a new category.

**Pull request merged**
