### PR TITLE
Document what happens upon first app launch

### PR DESCRIPTION
**Pull request by justinmayer**
End users should be informed regarding what will happen upon first launch of the application, including what directories are created, where downloaded models will be stored, what background processes will be launched, and what system-level changes will be made.

In the long run, hopefully these behaviors will be changed to allow for more flexibility and customization, but for now it is important for end users to have a clear understanding of what _currently_ happens when launching the application for the first time.

### CODE REVIEW

**Comment by panckreous** [comment]
Ooh, I really like this. Seems a perfect middle ground until https://github.com/jmorganca/ollama/issues/162 https://github.com/jmorganca/ollama/issues/153 https://github.com/jmorganca/ollama/issues/228 etc can make their way up the priority list.

**Comment by justinmayer** [comment]
@jmorganca / @mxyng: A month ago I submitted this PR to inform users what will happen when the Ollama is launched for the first time. With every day that passes, more and more people are trying Ollama for the first time without a clear understanding of what will happen — an understanding that is provided in the README additions contained in this pull request.

Would you please review this PR so we can get it merged posthaste?

**Comment by justinmayer** [comment]
As seen in the referenced issues above, new folks continue to find Ollama and get frustrated because they don't understand what happens on first launch, including where files are stored.

In order to prevent this unnecessary confusion for new users, would someone with a commit bit please review this pull request? 🙏

**Comment by justinmayer** [comment]
Could someone take five minutes to review this pull request and either merge it or post a comment here with some thoughts?

**Comment by mchiang0610** [comment]
Hi @justinmayer, thank you so much for submitting this. What you have written is really helpful, but I don't think it belongs to the default readme. The reason for this is to keep the main readme super simple for users to get started. That being said, I think we should do a reference doc in the future that explains how Ollama works under-the-hood for anyone who wants to tinker with this further. 

I actually feel bad for closing this because it's well written. The only reason is to keep the readme light (it's already a load of information that we should eventually take time to cleanup).

**Comment by justinmayer** [comment]
@mchiang0610: I could not disagree with this more vehemently. The entire point of this pull request is that it is **not** super simple for users to get started given that they have no way of understanding what will happen when trying Ollama for the first time. Plus, there are severe usability failures that this README calls attention to, and ultimately the impression left by this summary PR closure is that Ollama maintainers would rather sweep that fact under the rug and not further draw attention to it.

As an open source maintainer myself, I appreciate the hard and often selfless work that goes into it. But I also believe that projects are defined by their leadership, and by that measure, let's just say this experience has resulted in a vote of no-confidence from me.

**Comment by s-partridge** [comment]
This looks like critical information to me, that should have been included in the readme from the start. I'm surprised that this was shut down, especially when the discussion about this addition is abot 10 times as long as the addition itself.

I searched my filesystem manually to figure out where everything went because it wasn't clear at all from the installation (or instructions) what was happening.

**Comment by peterdonnelly1** [comment]
100% agree with the sentiments expressed in this thread.

Also, it is kind of annoying that all the tools (axolotl, LMStudio, ollama, probably others) maintain different and distinct caching directories and format; sometimes not even under ~/.cache (looking at you ollama), and ignoring the hugging face cache directory (~/.cache/huggingface) which is there for anyone to use

**Comment by s-partridge** [comment]
So that it's clear I'm not just here to criticize, I want to point out that past the initial hurdles, this is seems to be a solid, efficient, and robust application. Once I got it up and running and understood how the components work, it's quite smooth and uses surprisingly few resources for what it is.

The problem lies in the initial documentation, or lack thereof. It took longer than necessary for me to learn how the program functions because it wasn't apparent where or how things were stored (especially since the models themselves are stored in cryptic format I wasn't familiar with).

When I realized it had a background process, I checked to make sure it wasn't installing a service to run on startup without my consent (It doesn't, so bonus points for that). This reduces user trust in the project. I think it's important to have a list of things your application is going to do to the system if it's more than a single-directory package.

Honestly it doesn't need much. I'm not even asking for changes to the codebase. How the system functions does not bother me, I just want to know what it's going to do to my computer. I just think this stuff should just be laid out up-front clearly in the quick start docs or readme.

**Comment by dzhang314** [comment]
I would like to echo all the previous comments in this thread. It is unreasonable to me that an app which installs a system service that starts upon login doesn't TELL the user. This information needs to be front and center of both the installer and the README file.

The argument of "keeping the README file simple" doesn't even make sense because the README is currently polluted with this long list of hundreds of external integrations. That's a good list to have, don't get me wrong. But if you have space for that list, you have room to include this basic information.

**Comment by hichemfantar** [comment]
PR https://github.com/ollama/ollama/pull/7097 allows you to configure auto start behavior which closes https://github.com/ollama/ollama/issues/162

**Review by Node0 — COMMENTED** [review]
First of all thanks for your effort here, I can see from PR #7097 that you do polished work on the OS X side of things.
That PR should be merged as it's a good platform-specific change on a platform specific installer. 

Now this PR is a bit different as it has a very "Mac User" wording and orientation; what do I mean? Well take a look at this from your change:

```
...prompt you for administrative access in order to install
the command line executable, which in practice means symlinking 
`/Applications/Ollama.app/Contents/Resources/ollama`...
```
^^^^^^^ <- See that `Applications/Ollama/Contents`, these are all Mac OSX concerns, not linux at all, and certainly not windows, the point is, if you're going to do this, then "Do it well", Do it for all three platforms in a nice bulleted or sectioned style.

1.) The Mac OSX install is a zip that opens into an app, that when executed asks to move itself into the Applications folder, and then tells the user what it's doing and then tells the user what command to run in the terminal. It's the "Tesla Autopilot" version of all the Ollama installs.

2.) Windows is similar, you are guided through it step by step, but windows command line stuff is inherently harder due to the ambiguity of powershell vs WSL terminal and because WSL can access windows filesystem and do stuff so people often just use WSL to do terminal things. See what I mean? It's more complicated on windows.

3.) Now the linux install is fairly straightforward, but no GUI popups flash in front of the user, guiding them step-by-step on how to use Ollama. It could use some sprucing up, like "Hey here is where the models are kept, here is the file linking those weird sha looking files to the actual model names, etc" We don't have to tell them (though it's an excellent idea) where the systemctl ollama.service file is, but if we did and showed them how to add/remove environment variable lines and change startup options for ollama, that would actually be super helpful.

Now if you took the installation section and subdivided it into each of those 3 platforms, and then did a fairly decent job on each one, that would actually be awesome work and we could iterate on that and polish it.

If not, then it's better not to selectively document a single platform while neglecting the others. I can see how the reviewer would suggest that this type of platform specific documentation be located in a "getting started" style documentation guide, that would move it out of the main readme.md and let the technical writer develop the install docs without having to worry about keeping readme.md tidy, they could then go 100% and really document the install for all three platforms.

So yeah, makes alot of sense to do that, and cover all three platforms while doing so.

**Comment by hichemfantar** [comment]
@Node0 the problem is that different installers are being used for different platforms

the macos PR would work for all platforms if the electron build was also used in windows and linux.

**Pull request closed without merging**
