### PR TITLE
Add support for mixture of experts (MoE) and Mixtral

### LINKED ISSUE #1457: How to add MOE model Mistral 8x7B
Here is the model not sure how to add it to ollama 
https://huggingface.co/mattshumer/mistral-8x7b-chat

### LINKED ISSUE #1470: Will it be possible to run the new mixtral model quantized?
Hello, I know llama.cpp still doesn't support it, but this PR does https://github.com/ggerganov/llama.cpp/pull/4406
Is there a way to use it in ollama?

### LINKED ISSUE #1502: add mixtral-8x7b-v0.1 gguf model[from TheBloke] support
I download https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF, and create with ollama.

```
(base) ➜  Mixtral-8x7B-v0.1-GGUF ls
Modelfile                     mixtral-8x7b-v0.1.Q4_K_M.gguf
(base) ➜  Mixtral-8x7B-v0.1-GGUF cat Modelfile
FROM ./mixtral-8x7b-v0.1.Q4_K_M.gguf
(base) ➜  Mixtral-8x7B-v0.1-GGUF ollama create mixtral_8x7b_v0.1 -f Modelfile
transferring model data
creating model layer
using already created layer sha256:5e066c60d89d904db46c3bf577661040578a223a5a39ba3fd23ff091549767f0
writing layer sha256:fc2cce1b755caff29480bd61609c4c9fb495919d4af07adfe5b1a5ab0ffe5679
writing manifest
success
```

But not support when running it

```
(base) ➜  Mixtral-8x7B-v0.1-GGUF ollama run mixtral_8x7b_v0.1
Error: llama runner: failed to load model '/Users/mintisan/.ollama/models/blobs/sha256:5e066c60d89d904db41549767f0': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull mixtral_8x7b_v0.1:latest`
```

### PR DESCRIPTION
**Pull request by jmorganca**
To build this branch:

```
go generate ./...
go build .
```

```
./ollama serve

# in another terminal
./ollama run jmorgan/mixtral
```

resolves #1470 
resolves #1457 
resolves #1502

### CODE REVIEW

**Comment by phalexo** [comment]
> To build this branch:
> 
> ```
> go generate ./...
> go build .
> ```
> 
> ```
> ./ollama serve
> 
> # in another terminal
> ./ollama run jmorgan/mixtral
> ```
> 
> resolves #1470

This solved the Mixtral specific error, but it brought back the cuBLAS, fake OOM error.  0.1.11 does not generate this cuBLAS error but 0.1.13 and 0.1.14 do.

**Comment by jmorganca** [comment]
@phalexo thanks for the heads up and sorry to hear. Will definitely look into this

**Comment by Und3rf10w** [comment]
@phalexo , are you sure that's not just a lack of memory issue? I think by default `jmorgan/mixtral` uses the `q4_0` version, try instead running:  

`./ollama run jmorgan/mixtral:8x7b-instruct-v0.1-q2_K`

**Comment by phalexo** [comment]
This problem has nothing to do mixtral. It fails in exactly the same way on
a 5GiB model, version 0.1.11 works even on CodeLlama 34B.

**Comment by tmc** [comment]
As this is pointing to the https://github.com/ggerganov/llama.cpp/tree/mixtral branch I imagine we'll wait for that to merge for this to go in?

note: I had figured out how to get mixtral running not realizing this PR was already opened (tweeted about it [here](https://twitter.com/traviscline/status/1734763589750456566?s=61&t=A_CAsZ2Y5B45QuV_nmIMoQ) and as I was looking into it I realized that a lot of the patches in llama.cpp/patches are now unnecessary, I opened #1497 as a cleanup task.

**Comment by ehartford** [comment]
is there a way to make this run in the background instead of running it manually in a terminal?

**Comment by ehartford** [comment]
there is some kind of token issue

image

**Comment by iamwhatsall** [comment]
what is the hardware requirement for mac to run ollama Mixtral? Thanks.

**Comment by sweetcard** [comment]
@jmorganca Can I run Q6_K tag? Thanks

**Comment by svilupp** [comment]
> there is some kind of token issue, i wonder if this exist in llama.cpp too?
> 
> image


You should build the latest llama.cpp (main branch now, it has been merged).

There have been several subtle bugs in the Metal implementation that were causing early termination and spelling errors, see: https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1853523039

**Comment by justinh-rahb** [comment]
> > there is some kind of token issue, i wonder if this exist in llama.cpp too?
> > image
> 
> You should build the latest llama.cpp (main branch now, it has been merged).
> 
> There have been several subtle bugs in the Metal implementation that were causing early termination and spelling errors, see: [ggerganov/llama.cpp#4406 (comment)](https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1853523039)

@svilupp These seem to be resolved so long as you follow the prompt format exactly, according to @ggerganov

**Comment by phalexo** [comment]
@jmorganca Did the latest update have anything to do with the cuBLAS error? With version 0.1.11 working and later versions not working? I have rebuilt llama.ccp and ollama, but the problem persists. Should I checkout main for llama.cpp now and main for ollama? Or still build mixtral/moe branches?

llm_load_tensors: ggml ctx size =    0.39 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =  102.93 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors: VRAM used: 36497.55 MiB
⠦ .
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
⠇ llama_kv_cache_init: VRAM kv self = 256.00 MB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 187.35 MiB
⠏ llama_new_context_with_model: VRAM scratch buffer: 184.04 MiB
llama_new_context_with_model: total VRAM used: 36937.59 MiB (model: 36497.55 MiB, context: 440.04 MiB)
⠋ {"timestamp":1702483425,"level":"INFO","function":"main","line":3035,"message":"HTTP server listening","hostname":"127.0.0.1","port":60180}
⠙ {"timestamp":1702483425,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"127.0.0.1","remote_port":40854,"status":200,"method":"HEAD","path":"/","params":{}}
2023/12/13 11:03:45 llama.go:506: llama runner started in 18.201191 seconds
[GIN] 2023/12/13 - 11:03:45 | 200 | 19.164933508s |       127.0.0.1 | POST     "/api/generate"
>>> Hello
{"timestamp":1702483464,"level":"INFO","function":"log_server_request","line":2596,"message":"request","remote_addr":"127.0.0.1","remote_port":51334,"status":200,"method":"HEAD","path":"/","params":{}}

cuBLAS error 15 at /home/developer/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8049
current device: 0
GGML_ASSERT: /home/developer/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:8049: !"cuBLAS error"
memory allocation/deallocation mismatch at 0x5572d0320a20: allocated with malloc being deallocated with delete
⠙ 2023/12/13 11:04:26 llama.go:449: signal: aborted (core dumped)

**Comment by easp** [comment]
@phalexo since this isn't specifically about Mixtral, have you created a separate issue for it?

**Comment by phalexo** [comment]
> @phalexo since this isn't specifically about Mixtral, have you created a separate issue for it?

There were issues created by others. I thought that it was dealt with, but when I built the Mixtral branch the issue was back. The non-Mixtral version 0.1.11 does not have this problem, but since "moe" is derived from 0.1.14 the problem is back.

**Comment by miguelemosreverte** [comment]
> To build this branch:
  go generate ./... :white_check_mark:
  go build . :white_check_mark:
  ./ollama serve :white_check_mark:
  #in another terminal
  ./ollama run jmorgan/mixtral :x:

```
 ./ollama run jmorgan/mixtral

pulling manifest 
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/0c/0c57465507f21bed4364fca37efd310bee92e25a4ce4f5678ef9b44e95830e4e/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20231213%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20231213T204346Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=e148a119ed24926c91c111b4c4b3a3c9a74af577dd3b0e5a2e28329ef7f30fbd": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host
```

**Pull request merged**
