### PR TITLE
Remove already applied patches

### PR DESCRIPTION
**Pull request by avri-schneider**

### CODE REVIEW

**Comment by BruceMacD** [comment]
Hi @avri-schneider thanks for the contribution. These files need to be applied any time `go generate ./...` is run on a new computer so they should be kept. We dont actually commit the changes to the submodule.

**Comment by avri-schneider** [comment]
@BruceMacD but `go generate ./...` pulls the latest code from the submodule. The submodule already has the patches applied, so trying to apply them again will cause the described error.

**Comment by avri-schneider** [comment]
> We dont actually commit the changes to the submodule

https://github.com/ggerganov/llama.cpp/commit/c1ac54b77aaba10d029084d152be786102010eb2

**Comment by avri-schneider** [comment]
@jmorganca could you please take another look at this - I beleive that @BruceMacD is mistaken. You may want to try running `docker build` on a fresh clone of your repo and see it fails, then do the same on my fork.

**Pull request closed without merging**
